/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type HelixJS = HelixJs
export declare class HelixJs {
  constructor(user: string)
  query(queryId: string, jsonBody: string): string
}
